package baway.com.dyouyuan.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import baway.com.dyouyuan.bean.DataBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATA_BEAN".
*/
public class DataBeanDao extends AbstractDao<DataBean, Long> {

    public static final String TABLENAME = "DATA_BEAN";

    /**
     * Properties of entity DataBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Area = new Property(0, String.class, "area", false, "AREA");
        public final static Property PicWidth = new Property(1, int.class, "picWidth", false, "PIC_WIDTH");
        public final static Property Createtime = new Property(2, long.class, "createtime", false, "CREATETIME");
        public final static Property PicHeight = new Property(3, int.class, "picHeight", false, "PIC_HEIGHT");
        public final static Property Gender = new Property(4, String.class, "gender", false, "GENDER");
        public final static Property Lng = new Property(5, double.class, "lng", false, "LNG");
        public final static Property Introduce = new Property(6, String.class, "introduce", false, "INTRODUCE");
        public final static Property ImagePath = new Property(7, String.class, "imagePath", false, "IMAGE_PATH");
        public final static Property UserId = new Property(8, Long.class, "userId", true, "_id");
        public final static Property Yxpassword = new Property(9, String.class, "yxpassword", false, "YXPASSWORD");
        public final static Property Password = new Property(10, String.class, "password", false, "PASSWORD");
        public final static Property Lasttime = new Property(11, long.class, "lasttime", false, "LASTTIME");
        public final static Property Phone = new Property(12, String.class, "phone", false, "PHONE");
        public final static Property Nickname = new Property(13, String.class, "nickname", false, "NICKNAME");
        public final static Property Age = new Property(14, String.class, "age", false, "AGE");
        public final static Property Lat = new Property(15, double.class, "lat", false, "LAT");
    }


    public DataBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DataBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATA_BEAN\" (" + //
                "\"AREA\" TEXT," + // 0: area
                "\"PIC_WIDTH\" INTEGER NOT NULL ," + // 1: picWidth
                "\"CREATETIME\" INTEGER NOT NULL ," + // 2: createtime
                "\"PIC_HEIGHT\" INTEGER NOT NULL ," + // 3: picHeight
                "\"GENDER\" TEXT," + // 4: gender
                "\"LNG\" REAL NOT NULL ," + // 5: lng
                "\"INTRODUCE\" TEXT," + // 6: introduce
                "\"IMAGE_PATH\" TEXT," + // 7: imagePath
                "\"_id\" INTEGER PRIMARY KEY ," + // 8: userId
                "\"YXPASSWORD\" TEXT," + // 9: yxpassword
                "\"PASSWORD\" TEXT," + // 10: password
                "\"LASTTIME\" INTEGER NOT NULL ," + // 11: lasttime
                "\"PHONE\" TEXT," + // 12: phone
                "\"NICKNAME\" TEXT," + // 13: nickname
                "\"AGE\" TEXT," + // 14: age
                "\"LAT\" REAL NOT NULL );"); // 15: lat
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATA_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DataBean entity) {
        stmt.clearBindings();
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(1, area);
        }
        stmt.bindLong(2, entity.getPicWidth());
        stmt.bindLong(3, entity.getCreatetime());
        stmt.bindLong(4, entity.getPicHeight());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(5, gender);
        }
        stmt.bindDouble(6, entity.getLng());
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(7, introduce);
        }
 
        String imagePath = entity.getImagePath();
        if (imagePath != null) {
            stmt.bindString(8, imagePath);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(9, userId);
        }
 
        String yxpassword = entity.getYxpassword();
        if (yxpassword != null) {
            stmt.bindString(10, yxpassword);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(11, password);
        }
        stmt.bindLong(12, entity.getLasttime());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(13, phone);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(14, nickname);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(15, age);
        }
        stmt.bindDouble(16, entity.getLat());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DataBean entity) {
        stmt.clearBindings();
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(1, area);
        }
        stmt.bindLong(2, entity.getPicWidth());
        stmt.bindLong(3, entity.getCreatetime());
        stmt.bindLong(4, entity.getPicHeight());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(5, gender);
        }
        stmt.bindDouble(6, entity.getLng());
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(7, introduce);
        }
 
        String imagePath = entity.getImagePath();
        if (imagePath != null) {
            stmt.bindString(8, imagePath);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(9, userId);
        }
 
        String yxpassword = entity.getYxpassword();
        if (yxpassword != null) {
            stmt.bindString(10, yxpassword);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(11, password);
        }
        stmt.bindLong(12, entity.getLasttime());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(13, phone);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(14, nickname);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(15, age);
        }
        stmt.bindDouble(16, entity.getLat());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8);
    }    

    @Override
    public DataBean readEntity(Cursor cursor, int offset) {
        DataBean entity = new DataBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // area
            cursor.getInt(offset + 1), // picWidth
            cursor.getLong(offset + 2), // createtime
            cursor.getInt(offset + 3), // picHeight
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // gender
            cursor.getDouble(offset + 5), // lng
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // introduce
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // imagePath
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // userId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // yxpassword
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // password
            cursor.getLong(offset + 11), // lasttime
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // phone
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // nickname
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // age
            cursor.getDouble(offset + 15) // lat
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DataBean entity, int offset) {
        entity.setArea(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPicWidth(cursor.getInt(offset + 1));
        entity.setCreatetime(cursor.getLong(offset + 2));
        entity.setPicHeight(cursor.getInt(offset + 3));
        entity.setGender(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLng(cursor.getDouble(offset + 5));
        entity.setIntroduce(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImagePath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setYxpassword(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPassword(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLasttime(cursor.getLong(offset + 11));
        entity.setPhone(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setNickname(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAge(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setLat(cursor.getDouble(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DataBean entity, long rowId) {
        entity.setUserId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DataBean entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DataBean entity) {
        return entity.getUserId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
